Traceback:
2024-02-09 19:47:37.179109
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateCategory.py", line 24, in post
    data['type'] = data['type'][0]
                   ~~~~~~~~~~~~^^^
IndexError: string index out of range
==================================================
Traceback:
2024-02-09 19:48:10.399938
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateCategory.py", line 24, in post
    data['type'] = data['type'][0]
                   ~~~~~~~~~~~~^^^
IndexError: string index out of range
==================================================
