Traceback:
2024-01-30 20:30:30.829586
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateSubcategory.py", line 32, in post
    payload = services.create_subcategory()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/finances/services.py", line 33, in create_subcategory
    category = Category.objects.get(name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
finances.models.Category.DoesNotExist: Category matching query does not exist.
==================================================
Traceback:
2024-01-30 20:31:33.582319
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateSubcategory.py", line 32, in post
    payload = services.create_subcategory()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/finances/services.py", line 33, in create_subcategory
    category = Category.objects.get(name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
finances.models.Category.DoesNotExist: Category matching query does not exist.
==================================================
Traceback:
2024-01-30 20:32:39.094136
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateSubcategory.py", line 32, in post
    payload = services.create_subcategory()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/finances/services.py", line 33, in create_subcategory
    category = Category.objects.get(name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
finances.models.Category.DoesNotExist: Category matching query does not exist.
==================================================
Traceback:
2024-01-30 20:32:59.681003
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateSubcategory.py", line 32, in post
    payload = services.create_subcategory()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/finances/services.py", line 33, in create_subcategory
    category = Category.objects.get(name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
finances.models.Category.DoesNotExist: Category matching query does not exist.
==================================================
Traceback:
2024-01-30 20:33:12.248125
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateSubcategory.py", line 28, in post
    if not serializer.is_valid():
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/finances/serializers.py", line 21, in to_internal_value
    print(Category.objects.all().name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'name'
==================================================
Traceback:
2024-01-30 20:33:54.886536
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateSubcategory.py", line 32, in post
    payload = services.create_subcategory()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/finances/services.py", line 33, in create_subcategory
    category = Category.objects.get(name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
finances.models.Category.DoesNotExist: Category matching query does not exist.
==================================================
Traceback:
2024-01-30 20:34:21.174133
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateSubcategory.py", line 32, in post
    payload = services.create_subcategory()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/finances/services.py", line 33, in create_subcategory
    category = Category.objects.get(name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
finances.models.Category.DoesNotExist: Category matching query does not exist.
==================================================
Traceback:
2024-01-30 20:36:05.626601
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateSubcategory.py", line 32, in post
    payload = services.create_subcategory()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/finances/services.py", line 33, in create_subcategory
    category = Category.objects.get(name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
finances.models.Category.DoesNotExist: Category matching query does not exist.
==================================================
Traceback:
2024-01-30 20:36:29.779569
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateSubcategory.py", line 32, in post
    payload = services.create_subcategory()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/finances/services.py", line 33, in create_subcategory
    category = Category.objects.get(name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
finances.models.Category.DoesNotExist: Category matching query does not exist.
==================================================
Traceback:
2024-01-30 20:37:10.086844
Traceback (most recent call last):
  File "/home/kesley/Documents/house-management/backend/finances/views/CreateSubcategory.py", line 32, in post
    payload = services.create_subcategory()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/finances/services.py", line 33, in create_subcategory
    category = Category.objects.get(name=name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kesley/Documents/house-management/backend/venv/lib/python3.11/site-packages/django/db/models/query.py", line 647, in get
    raise self.model.DoesNotExist(
finances.models.Category.DoesNotExist: Category matching query does not exist.
==================================================
Serializer Errors:
2024-01-30 20:40:01.384240
{'category': [ErrorDetail(string='Incorrect type. Expected pk value, received str.', code='incorrect_type')], 'subcategory': [ErrorDetail(string='Incorrect type. Expected pk value, received str.', code='incorrect_type')]}==================================================
